import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
import 'app.dart';
// import 'firebase_options.dart'; // To be generated by FlutterFire CLI

import 'package:provider/provider.dart';
import 'data/repositories/auth_repository.dart';
import 'data/repositories/worker_repository.dart';
import 'data/repositories/booking_repository.dart';
import 'data/repositories/admin_repository.dart';
import 'features/auth/presentation/viewmodels/auth_viewmodel.dart';
import 'features/worker/presentation/viewmodels/worker_viewmodel.dart';
import 'features/customer/presentation/viewmodels/customer_home_viewmodel.dart';
import 'features/customer/presentation/viewmodels/booking_viewmodel.dart';
import 'features/admin/presentation/viewmodels/admin_dashboard_viewmodel.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthViewModel(AuthRepository())),
        ChangeNotifierProvider(create: (_) => WorkerViewModel(WorkerRepository())),
        ChangeNotifierProvider(create: (_) => CustomerViewModel(BookingRepository())),
        ChangeNotifierProvider(create: (_) => BookingViewModel(BookingRepository())),
        ChangeNotifierProvider(create: (_) => AdminViewModel(AdminRepository())),
      ],
      child: const HomeServiceApp(),
    ),
  );
}
